# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite-plugins/buildkite-plugin-linter/master/lib/plugin-yaml-schema.yml
name: DRA Prep
description: Generate DRA build id, manifest, and summary for the artifacts produced in this step, and upload them to the Buildkite store.
author: https://github.com/elastic
requirements: []
configuration:
  properties:
    product_id:
      type: string
    stack_version:
      type: string
    workflow:
      type: string
      enum: [snapshot, staging]
    fail_on_diff:
      type: boolean
    upload:
      type: boolean
  required:
    - product_id
    - stack_version
    - workflow
  additionalProperties: false
