---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: ":white_check_mark: Pre-commit"
    command: "python3.12 -mpip install pre-commit==4.6.0 && python3.12 -mpre_commit run --from-ref origin/HEAD --to-ref HEAD --show-diff-on-failure"
    plugins:
      - elastic/hermit#v1.0.2
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential:latest@sha256:f25d024a1b9e2490c6201a2ef9822d73e604911e1a616d0f2b02537e5176f66c"

  - label: ":test_tube: Test"
    command: "bats tests/"
    plugins:
      - elastic/hermit#v1.0.2
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential:latest@sha256:f25d024a1b9e2490c6201a2ef9822d73e604911e1a616d0f2b02537e5176f66c"

  - label: ":buildkite: Validate plugin"
    plugins:
      - plugin-linter#v3.3.0:
          id: elastic/dra-prep
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2204

  - label: ":smoke: Integration test"
    command: ".buildkite/scripts/integration-test.sh"
    plugins:
      - elastic/dra-prep#$BUILDKITE_COMMIT:
          product_id: smoke-test
          stack_version: "9.5.0-SNAPSHOT"
          workflow: snapshot
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential:latest@sha256:f25d024a1b9e2490c6201a2ef9822d73e604911e1a616d0f2b02537e5176f66c"
