---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: ":shell: Lint"
    command: "bin/shellcheck hooks/post-command"
    agents:
      image: "docker.elastic.co/ci-agent-images/pipelib:0.27.0@sha256:d1713778d27e0b6208f59ba8761f04ef033af4c4237cb2614a09d38584c5ff88"

  - label: ":test_tube: Test"
    command: "bin/bats tests/"
    agents:
      image: "docker.elastic.co/ci-agent-images/pipelib:0.27.0@sha256:d1713778d27e0b6208f59ba8761f04ef033af4c4237cb2614a09d38584c5ff88"

  - label: ":buildkite: Validate plugin"
    plugins:
      - plugin-linter#v3.3.0:
          id: elastic/dra-prep
